//  Hover over each for an example of what they do

// https://nodejs.dev/en/api/v19/process/

process.constructor()

process._debugEnd
process._debugProcess
process._events
process._eventsCount
process._exiting
process._fatalException
process._getActiveHandles
process._getActiveRequests
process._kill
process._linkedBinding
process._maxListeners
process._preload_modules
process._rawDebug
process._startProfilerIdleNotifier
process._stopProfilerIdleNotifier
process._tickCallback
process.abort
process.allowedNodeEnvironmentFlags
process.arch
process.argv
process.argv0
process.assert
process.binding
process.chdir
process.config
process.cwd
process._debugEnd
process.debugPort
process.dlopen
process.domain
process.emitWarning
process.env
process.execArgv
process.execPath
process.exit
process.features
process.getActiveResourcesInfo
process.hasUncaughtExceptionCaptureCallback
process.hrtime
process.kill
process.memoryUsage
process.moduleLoadList
process.nextTick
process.openStdin
process.pid
process.platform
process.ppid
process.reallyExit
process.release
process.report
process.resourceUsage
process.setSourceMapsEnabled
process.setUncaughtExceptionCaptureCallback
process.stderr
process.stdin
process.stdout
process.title
process.umask
process.uptime
process.version
process.versions